_defaults: &defaults
  run: &getDeps go get -v -t -d ./...

_docker_worker: &docker_worker
  - image: circleci/golang:1.11
_workdir: &work_dir /go/src/github.com/aeternas/SwadeshNess-IntegrationTests

_git_checkout: &git_checkout
  name: Checkout
  command: |
    mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    git clone --depth=50 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
    git checkout $CIRCLE_SHA1

_attach_workspace: &attach_workspace
  at: /go/src/github.com/aeternas/SwadeshNess-IntegrationTests

version: 2
jobs:
  checkout:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - run: *git_checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-master-
          - v1-dep-
      - run: *getDeps
      - save_cache:
         key: v1-dep-{{ .Branch }}-{{ epoch }}
         paths:
         - vendor/bundle
         - ~/virtualenvs
         - ~/.m2
         - ~/.ivy2
         - ~/.bundle
         - ~/.go_workspace
         - ~/.gradle
         - ~/.cache/bower
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *getDeps
      - run: 
          name: linting
          command: go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
  test:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *getDeps
      - run:
          name: tests
          command: go test -v ./...
  deploy:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Containerize, Push and Deploy
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t aeternas/swadeshness-tests:$CIRCLE_BRANCH . && \
            docker push aeternas/swadeshness-tests:$CIRCLE_BRANCH
workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - deploy:
          requires:
            - lint
            - test
